### ISSUE TITLE
JS table problem

### ISSUE THREAD

**Issue by kmelia** [frocher/sofreakingboring#7]
Hi,
There is a bug on fast writing into the table, some character does not pass.
Additionally, you cannot use the DEL key to reset to the default content.

---

Tested on Firefox 34.0.5 / Windows 7 Pro

**Comment by kmelia** [comment]
Handsontable 0.12.3 seems to resolve these bugs.
I have tried to reproduce them on their [demo website](http://handsontable.com)

**Comment by frocher** [comment]
Upgrade to 0.12.3 is ready, could you test it to see if it's better with FF ?

**Comment by kmelia** [comment]
I tested and it's better.
Thanks.
